services:
  jobhuntlogger:
    container_name:
      blazorapp
    build:
      context: .
      dockerfile: JobHuntLogger\Dockerfile
      # target: dev
    volumes:
       # - ./JobHuntLogger:/src/JobHuntLogger
       - ./dataprotection-keys:/root/.aspnet/DataProtection-Keys
    ports:
     - "8000:8080"
    secrets:
     - dbinfo
     

  jobhuntapi:
    container_name:
       jobhuntapi
    build:
      context: .
      dockerfile: JobHuntAPI\Dockerfile
    ports:
       - "8160:8080"
    secrets:
     - dbinfo
     - apiinfo

       

secrets:
   dbinfo:
      file: ./docker/secrets/dbinfo.json
   apiinfo:
      file: ./docker/secrets/api.json
