services:
  jobhuntlogger:
    container_name:
      blazorapp
    build:
      context: .
      dockerfile: JobHuntLogger\Dockerfile
    ports:
     - "8000:8080"

  jobhuntapi:
    container_name:
       jobhuntapi
    build:
      context: .
      dockerfile: JobHuntAPI\Dockerfile
    # logins and creation is redirection by authorizationserver, so no ports exposed
    # ports:
    #   - "8160:8080"
    secrets:
     - dbinfo

        
  authorizationserver:
     container_name:
      authorizationserver
     build:
       context: .
       dockerfile: AuthorizationServer\Dockerfile
     volumes:
       - ./dataprotection-keys:/root/.aspnet/DataProtection-Keys
     ports:
       - "8180:8080"
     secrets:
       - dbinfo


secrets:
   dbinfo:
      file: ./docker/secrets/dbinfo.json
