// <auto-generated />
using System;
using JobHuntAPI.Repository;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace JobHuntAPI.Migrations
{
    [DbContext(typeof(ApplicationContext))]
    [Migration("20251024080015_PdfAsList")]
    partial class PdfAsList
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("JobHuntAPI.Model.JobApplication", b =>
                {
                    b.Property<Guid>("JobApplicationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("AppliedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Company")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("Deadline")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("JobTitle")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("ReplyDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("JobApplicationId");

                    b.ToTable("Applications");
                });

            modelBuilder.Entity("JobHuntAPI.Model.PdfFile", b =>
                {
                    b.Property<Guid>("PdfFileId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<byte[]>("Content")
                        .IsRequired()
                        .HasColumnType("bytea");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("JobApplicationId")
                        .HasColumnType("uuid");

                    b.Property<string>("PdfType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("PdfFileId");

                    b.HasIndex("JobApplicationId");

                    b.ToTable("PdfFiles");
                });

            modelBuilder.Entity("JobHuntAPI.Model.PdfFile", b =>
                {
                    b.HasOne("JobHuntAPI.Model.JobApplication", null)
                        .WithMany("PdfFiles")
                        .HasForeignKey("JobApplicationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("JobHuntAPI.Model.JobApplication", b =>
                {
                    b.Navigation("PdfFiles");
                });
#pragma warning restore 612, 618
        }
    }
}
